/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VendedorRouteImport } from './routes/vendedor'
import { Route as ResetRouteImport } from './routes/reset'
import { Route as RegistroGaleriaRouteImport } from './routes/registro-galeria'
import { Route as RegistroAmbulanteRouteImport } from './routes/registro-ambulante'
import { Route as RecuperarRouteImport } from './routes/recuperar'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LicenciaRouteImport } from './routes/licencia'
import { Route as ConfirmacionRouteImport } from './routes/confirmacion'
import { Route as IndexRouteImport } from './routes/index'

const VendedorRoute = VendedorRouteImport.update({
  id: '/vendedor',
  path: '/vendedor',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetRoute = ResetRouteImport.update({
  id: '/reset',
  path: '/reset',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistroGaleriaRoute = RegistroGaleriaRouteImport.update({
  id: '/registro-galeria',
  path: '/registro-galeria',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistroAmbulanteRoute = RegistroAmbulanteRouteImport.update({
  id: '/registro-ambulante',
  path: '/registro-ambulante',
  getParentRoute: () => rootRouteImport,
} as any)
const RecuperarRoute = RecuperarRouteImport.update({
  id: '/recuperar',
  path: '/recuperar',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LicenciaRoute = LicenciaRouteImport.update({
  id: '/licencia',
  path: '/licencia',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmacionRoute = ConfirmacionRouteImport.update({
  id: '/confirmacion',
  path: '/confirmacion',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/confirmacion': typeof ConfirmacionRoute
  '/licencia': typeof LicenciaRoute
  '/login': typeof LoginRoute
  '/recuperar': typeof RecuperarRoute
  '/registro-ambulante': typeof RegistroAmbulanteRoute
  '/registro-galeria': typeof RegistroGaleriaRoute
  '/reset': typeof ResetRoute
  '/vendedor': typeof VendedorRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/confirmacion': typeof ConfirmacionRoute
  '/licencia': typeof LicenciaRoute
  '/login': typeof LoginRoute
  '/recuperar': typeof RecuperarRoute
  '/registro-ambulante': typeof RegistroAmbulanteRoute
  '/registro-galeria': typeof RegistroGaleriaRoute
  '/reset': typeof ResetRoute
  '/vendedor': typeof VendedorRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/confirmacion': typeof ConfirmacionRoute
  '/licencia': typeof LicenciaRoute
  '/login': typeof LoginRoute
  '/recuperar': typeof RecuperarRoute
  '/registro-ambulante': typeof RegistroAmbulanteRoute
  '/registro-galeria': typeof RegistroGaleriaRoute
  '/reset': typeof ResetRoute
  '/vendedor': typeof VendedorRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/confirmacion'
    | '/licencia'
    | '/login'
    | '/recuperar'
    | '/registro-ambulante'
    | '/registro-galeria'
    | '/reset'
    | '/vendedor'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/confirmacion'
    | '/licencia'
    | '/login'
    | '/recuperar'
    | '/registro-ambulante'
    | '/registro-galeria'
    | '/reset'
    | '/vendedor'
  id:
    | '__root__'
    | '/'
    | '/confirmacion'
    | '/licencia'
    | '/login'
    | '/recuperar'
    | '/registro-ambulante'
    | '/registro-galeria'
    | '/reset'
    | '/vendedor'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConfirmacionRoute: typeof ConfirmacionRoute
  LicenciaRoute: typeof LicenciaRoute
  LoginRoute: typeof LoginRoute
  RecuperarRoute: typeof RecuperarRoute
  RegistroAmbulanteRoute: typeof RegistroAmbulanteRoute
  RegistroGaleriaRoute: typeof RegistroGaleriaRoute
  ResetRoute: typeof ResetRoute
  VendedorRoute: typeof VendedorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vendedor': {
      id: '/vendedor'
      path: '/vendedor'
      fullPath: '/vendedor'
      preLoaderRoute: typeof VendedorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset': {
      id: '/reset'
      path: '/reset'
      fullPath: '/reset'
      preLoaderRoute: typeof ResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registro-galeria': {
      id: '/registro-galeria'
      path: '/registro-galeria'
      fullPath: '/registro-galeria'
      preLoaderRoute: typeof RegistroGaleriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registro-ambulante': {
      id: '/registro-ambulante'
      path: '/registro-ambulante'
      fullPath: '/registro-ambulante'
      preLoaderRoute: typeof RegistroAmbulanteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recuperar': {
      id: '/recuperar'
      path: '/recuperar'
      fullPath: '/recuperar'
      preLoaderRoute: typeof RecuperarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/licencia': {
      id: '/licencia'
      path: '/licencia'
      fullPath: '/licencia'
      preLoaderRoute: typeof LicenciaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirmacion': {
      id: '/confirmacion'
      path: '/confirmacion'
      fullPath: '/confirmacion'
      preLoaderRoute: typeof ConfirmacionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConfirmacionRoute: ConfirmacionRoute,
  LicenciaRoute: LicenciaRoute,
  LoginRoute: LoginRoute,
  RecuperarRoute: RecuperarRoute,
  RegistroAmbulanteRoute: RegistroAmbulanteRoute,
  RegistroGaleriaRoute: RegistroGaleriaRoute,
  ResetRoute: ResetRoute,
  VendedorRoute: VendedorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
